services:
  postgres_db:
    container_name: url-shortener-database
    image: postgres:latest
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', $DB_NAME, '-U', $DB_USER]
      interval: 5s
      retries: 5
    restart: always
  app:
    container_name: url-shortener-app
    build:
      context: ./app
    image: url-shortener/app
    restart: always
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    links:
      - postgres_db:db

volumes:
  postgres_db:
    driver: local
